### - Teste da Rota Raiz
GET http://localhost:3000/
Content-Type: application/json

### - Teste cadastro do usuário 1
POST http://localhost:3000/usuario
Content-Type: application/json

{
    "nome": "Moisés",
    "email": "moises@gmail.com",
    "senha": "abc123"
}

### - Teste cadastro do usuário 2
POST http://localhost:3000/usuario
Content-Type: application/json

{
    "nome": "Ana",
    "email": "ana@gmail.com",
    "senha": "123"
}

### - Teste cadastro do usuário 3
POST http://localhost:3000/usuario
Content-Type: application/json

{
    "nome": "Bruno",
    "email": "bruno@gmail.com",
    "senha": "456"
}

### - Teste cadastro do usuário 4
POST http://localhost:3000/usuario
Content-Type: application/json

{
    "nome": "Diego",
    "email": "diego@gmail.com",
    "senha": "789"
}